#!/bin/bash
#PBS -S /bin/bash 
#PBS -N equilel
#PBS -l walltime=2:00:00
#PBS -l nodes=1:ppn=12
#PBS -l mem=2000mb

cd $PBS_O_WORKDIR

echo "Node file: $PBS_NODEFILE :"
echo "---------------------"
cat $PBS_NODEFILE
echo "---------------------"
NUM_PROCS=`/bin/awk 'END {print NR}' $PBS_NODEFILE`
echo "Running on $NUM_PROCS processors."
echo ""

module load application/gromacs/4.6.1  

time mpiexec -n ${NUM_PROCS} mdrun_mpi -v -deffnm water
